name: C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: ${{ matrix.compiler.name }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: GCC
            cc: gcc
            cxx: g++

          - name: Clang
            cc: clang
            cxx: clang++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Show toolchain
        run: |
          ${{ matrix.compiler.cxx }} --version
          cmake --version

      - name: Configure
        run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure
